# Generated by Django 4.0.1 on 2022-01-13 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bid_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('pet_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bid_app.pet')),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owen_pets_bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='petbid',
            constraint=models.UniqueConstraint(fields=('pet_bidder', 'pet_id'), name='pets_bids'),
        ),
    ]
